- name: Understanding precedence of variables
  hosts: dbgroup
  become: yes
  #vars:
  #  USRNAME: playuser
  #  COMM: variable from playbook
  tasks:
    - name: create a user
      user:
        name: "{{USRNAME}}"
        comment: "{{COMM}}"
      register: OUT

    - debug:
        var: OUT

    - debug:
        var: OUT.name
    
    - debug:
        var: OUT.comment

